Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: react-codebuild-name
      Description: Code build project for deployment to S3 bucket.
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        # Runtime: Standard # this is unsupported.
        Image: aws/codebuild/standard:2.0
      Source: 
        Type: CODECOMMIT
        # Buildspec: buildspec.yaml # this is unsupported.
        Location: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/react-repo-name
      TimeoutInMinutes: 60
      Cache:
        Type: NO_CACHE
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: react-codebuild-policy-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
                Effect: Allow
                Resource: '*'
              - Action:
                - 's3:PutObject'
                - 's3:GetObject'
                - 's3:GetObjectVersion'
                - 's3:GetBucketAcl'
                - 's3:GetBucketLocation'
                Effect: Allow
                Resource: 'arn:aws:s3:::codepipeline-us-east-1-*'
        - PolicyName: REACT_AmazonS3FullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 's3:*'
                Resource: '*'
                Effect: 'Allow'